Homework2
made-ml-in-prod-2021/l3lush pull request #3
Opened 2021-05-18 18:09 UTC by l3lush

Доброго времени суток!
Самооценка:
0) назвал ветку homework2, положил новый код в папку online_inference
1) Обернул модель в REST сервис (+3 балла)
2) Написал тесты для /predict/ (+3 балла)
3) Написал скрипт, который делает запросы к сервису (+2 балла)
4) Сделал валидацию данных, согласно описанию (+3 доп. балла)
5) Написал docker file (+4 балла)
6) НЕ оптимизировал размер (+0 баллов)
7) Опубликовал образ в hub.docker.com (+2 балла)
8) Полностью описал скрипт выполнения (+1 балл)

Провел самооценку +1 балл
ИТОГО: 3 + 3 + 2 + 3 + 4 + 0 + 2 + 1 + 1 = 19 баллов

2021-05-19 16:54 UTC, panda1987DS commented on online_inference/README.md
> +docker pull l3lush/online_inference:v1
На https://hub.docker.com/ уже есть v2 точно нужна v1?

2021-05-19 16:54 UTC, panda1987DS commented on online_inference/src/beta_app.py
> +import uvicorn
А зачем этот модуль?

2021-05-19 16:54 UTC, panda1987DS commented on online_inference/src/app.py
> +) -> List[TargetResponse]:
Ничего не логируется(

2021-05-19 16:54 UTC, panda1987DS commented on online_inference/src/data/data_validation.py
> +    etalon_df.drop(['target'], axis=1, inplace=True)
Кажется не лучшим решением, при валидации данных сначала скачивать весь датасет.

2021-05-19 16:54 UTC, panda1987DS commented on online_inference/README.md
> +    │   │   ├── predict_model.py
Сбивает с толку наличие в структуре и в папках пустых файлов.

2021-05-19 16:54 UTC, panda1987DS commented on online_inference/src/data/data_validation.py
> +    etalon_features = etalon_df.columns.to_list()
А что будет, если список фич передадут правильно, а количество колонок данных будет больше или меньше чем фич?

2021-05-22 18:46 UTC, Mikhail-M requested changes
удаляем .venv

2021-05-25 16:54 UTC, l3lush commented on online_inference/src/data/data_validation.py
> +    etalon_features = etalon_df.columns.to_list()
Вывалится ошибка, так как поступаемые данные будут не той же структуры, что и train выборка.

2021-05-25 16:55 UTC, l3lush commented on online_inference/README.md
> +docker pull l3lush/online_inference:v1
Да, можно использовать как v1, так и v2. Различия между ними не критичны.

2021-05-25 17:06 UTC, l3lush commented on online_inference/src/beta_app.py
> +import uvicorn
Это был тестовый запуск приложения, стоит удалить. Вы правы, оно бесполезно.

2021-05-25 17:06 UTC, l3lush commented on online_inference/src/app.py
> +) -> List[TargetResponse]:
Исправлено в новой версии, спасибо!

2021-05-25 17:07 UTC, l3lush commented on online_inference/src/data/data_validation.py
> +    etalon_df.drop(['target'], axis=1, inplace=True)
Справедливо, но иначе не получилось реализовать с наименьшими трудозатратами.

2021-05-25 17:07 UTC, l3lush commented on online_inference/README.md
> +    │   │   ├── predict_model.py
Удалено в новой версии, спасибо!

2021-05-27 08:09 UTC, Mikhail-M approved these changes
По валидации -- за старание 1 балл, но так нельзя делать, как верно заметили в комментах, можно будет потом изучить другие работы

Тесты 2 балла -- было бы замечательно, если бы на уровне модульных тестов, тестировалась не прод моделька, а  готовилась фикстурой, либо мокалась

Баллы: 16

2021-05-28 07:39 UTC, merged